// The identity server's directory, as head office uses it (OB-15-c · ADR-0019 · M02-FR-01 · M02-FR-04).
//
// Head office creates a named person's sign-in and turns a leaver's off — through the identity server's own admin
// interface, as the realm's `sre-provisioner` client. That client may manage users and nothing else (no realm settings,
// no clients, no roles beyond mapping the one second-factor role), and its secret is generated BY the identity server
// on first start and copied into head office's environment by the administrator: it is never in this repository, a
// realm file, an image or a log (hard rule #4).
//
// What this module never does: keep a password. A one-time password is handed in, set as TEMPORARY (the person must
// choose their own at first sign-in), and forgotten; it appears in no error, no log and no return value.

/** A person to give a sign-in to. */
export interface DirectoryPerson {
  /** The sign-in name the person types (the staff ID), lower case. */
  readonly username: string;
  /** The product's id for the person — the `sre_user_id` claim every token carries. */
  readonly userId: string;
  readonly displayName: string;
  /** Holds the second-factor role: the identity server asks for a one-time code after the password. */
  readonly secondFactor: boolean;
  /** Set as temporary; the person replaces it at first sign-in. Never stored or logged. */
  readonly temporaryPassword: string;
}

export type IssueOutcome =
  | { readonly result: 'issued'; readonly resumed: boolean }
  /** The sign-in name is already somebody else's, or this person already has a sign-in made elsewhere. */
  | { readonly result: 'refused'; readonly code: 'username_taken' | 'person_already_has_a_sign_in'; readonly detail: string };

export interface IdentityDirectory {
  /**
   * Give `person` a sign-in. `resume` is true when head office's ledger holds an unfinished attempt for this same person
   * (a reply that never arrived): an existing entry with this same name AND product id is then completed — a new
   * one-time password set, the second factor mapped, enabled — rather than refused.
   */
  readonly issue: (person: DirectoryPerson, resume: boolean) => Promise<IssueOutcome>;
  /** Turn a person's sign-in off and end their open identity-server sessions. `none` when they have no sign-in. */
  readonly end: (userId: string) => Promise<'ended' | 'none'>;
}

/** A refusal from the identity server, said without anything the request carried. */
export class DirectoryUnavailableError extends Error {
  constructor(what: string) { super(`identity server: ${what}`); this.name = 'DirectoryUnavailableError'; }
}

export interface KeycloakDirectorySettings {
  /** The identity server's base on the private network, e.g. http://idp:8080/auth. */
  readonly baseUrl: string;
  readonly realm: string;
  readonly clientId: string;
  readonly clientSecret: string;
  /** The realm role that makes the identity server ask for a one-time code. */
  readonly secondFactorRole: string;
  readonly fetch: typeof globalThis.fetch;
  readonly now?: () => number;
}

/** The base and realm of an identity server, read from its key-set address (…/auth/realms/<realm>/protocol/…). */
export function directoryLocationOf(jwksUrl: string): { readonly baseUrl: string; readonly realm: string } | undefined {
  const m = /^(https?:\/\/[^?#]+?)\/realms\/([^/?#]+)\/protocol\/openid-connect\/certs$/.exec(jwksUrl.trim());
  return m === null ? undefined : { baseUrl: m[1]!, realm: decodeURIComponent(m[2]!) };
}

interface KcUser { readonly id: string; readonly username: string; readonly enabled?: boolean; readonly attributes?: Record<string, readonly string[]> }

/** The identity server's admin interface, as the provisioner client. */
export function keycloakDirectory(s: KeycloakDirectorySettings): IdentityDirectory {
  const base = s.baseUrl.replace(/\/+$/, '');
  const admin = `${base}/admin/realms/${encodeURIComponent(s.realm)}`;
  const now = s.now ?? Date.now;
  let token: { value: string; until: number } | undefined;

  const accessToken = async (): Promise<string> => {
    if (token !== undefined && now() < token.until) return token.value;
    let res: Response;
    try {
      res = await s.fetch(`${base}/realms/${encodeURIComponent(s.realm)}/protocol/openid-connect/token`, {
        method: 'POST',
        headers: { 'content-type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({ grant_type: 'client_credentials', client_id: s.clientId, client_secret: s.clientSecret }).toString(),
        signal: AbortSignal.timeout(5000),
      });
    } catch { throw new DirectoryUnavailableError('not reachable'); }
    if (!res.ok) throw new DirectoryUnavailableError(`refused head office's provisioner (${res.status}) — check the provisioner secret`);
    const body = await res.json() as { access_token?: unknown; expires_in?: unknown };
    if (typeof body.access_token !== 'string') throw new DirectoryUnavailableError('answered without a token');
    const life = typeof body.expires_in === 'number' ? body.expires_in : 60;
    token = { value: body.access_token, until: now() + Math.max(0, life - 30) * 1000 };
    return token.value;
  };

  const call = async (method: string, path: string, body?: unknown): Promise<Response> => {
    const bearer = await accessToken();
    try {
      return await s.fetch(`${admin}${path}`, {
        method,
        headers: { authorization: `Bearer ${bearer}`, ...(body === undefined ? {} : { 'content-type': 'application/json' }), accept: 'application/json' },
        ...(body === undefined ? {} : { body: JSON.stringify(body) }),
        signal: AbortSignal.timeout(5000),
      });
    } catch { throw new DirectoryUnavailableError('not reachable'); }
  };
  const must = async (res: Response, what: string): Promise<Response> => {
    if (!res.ok) throw new DirectoryUnavailableError(`${what} refused (${res.status})`);
    return res;
  };

  const byUsername = async (username: string): Promise<KcUser | undefined> => {
    const res = await must(await call('GET', `/users?exact=true&briefRepresentation=false&username=${encodeURIComponent(username)}`), 'looking a person up');
    return ((await res.json()) as KcUser[]).find((u) => u.username === username);
  };
  const byUserId = async (userId: string): Promise<KcUser | undefined> => {
    const res = await must(await call('GET', `/users?exact=true&briefRepresentation=false&q=${encodeURIComponent(`sre_user_id:${userId}`)}`), 'looking a person up');
    return ((await res.json()) as KcUser[]).find((u) => (u.attributes?.['sre_user_id'] ?? []).includes(userId));
  };
  const productIdOf = (u: KcUser): string | undefined => u.attributes?.['sre_user_id']?.[0];

  // The whole representation is sent back with only `enabled` changed — a partial one may clear what it leaves out.
  const setEnabled = async (id: string, enabled: boolean, what: string): Promise<void> => {
    const current = await (await must(await call('GET', `/users/${encodeURIComponent(id)}`), 'reading the person')).json() as Record<string, unknown>;
    await must(await call('PUT', `/users/${encodeURIComponent(id)}`, { ...current, enabled }), what);
  };
  const setPassword = async (id: string, value: string): Promise<void> => {
    await must(await call('PUT', `/users/${encodeURIComponent(id)}/reset-password`, { type: 'password', value, temporary: true }), 'setting the one-time password');
  };
  const mapSecondFactor = async (id: string): Promise<void> => {
    // Read from the roles THIS person may be given — the provisioner may map roles, not read the realm's settings.
    const available = await (await must(await call('GET', `/users/${encodeURIComponent(id)}/role-mappings/realm/available`), 'reading the roles a person may hold')).json() as { id: string; name: string }[];
    const role = available.find((r) => r.name === s.secondFactorRole);
    if (role === undefined) {
      const held = await (await must(await call('GET', `/users/${encodeURIComponent(id)}/role-mappings/realm`), 'reading the person\'s roles')).json() as { name: string }[];
      if (held.some((r) => r.name === s.secondFactorRole)) return;
      throw new DirectoryUnavailableError(`has no "${s.secondFactorRole}" role for this person`);
    }
    await must(await call('POST', `/users/${encodeURIComponent(id)}/role-mappings/realm`, [{ id: role.id, name: role.name }]), 'requiring the second factor');
  };

  return {
    issue: async (person, resume) => {
      const sameName = await byUsername(person.username);
      const sameId = await byUserId(person.userId);
      if (sameName !== undefined && productIdOf(sameName) !== person.userId) {
        return { result: 'refused', code: 'username_taken', detail: `The sign-in name "${person.username}" already belongs to somebody else in the identity server.` };
      }
      if (sameId !== undefined && sameId.username !== person.username) {
        return { result: 'refused', code: 'person_already_has_a_sign_in', detail: `${person.userId} already has a sign-in, under another name, made in the identity server directly.` };
      }
      let id: string;
      let resumed = false;
      if (sameName !== undefined) {
        // Same name, same product id. Only an unfinished attempt of OUR OWN may be completed — never a sign-in somebody
        // already uses, whose password this would replace.
        if (!resume) {
          return { result: 'refused', code: 'person_already_has_a_sign_in', detail: `${person.userId} already has a sign-in in the identity server.` };
        }
        id = sameName.id;
        resumed = true;
      } else {
        // Created switched OFF: nobody can sign in with it until the second factor is in place.
        const res = await call('POST', '/users', {
          username: person.username, enabled: false, firstName: person.displayName,
          attributes: { sre_user_id: [person.userId] },
        });
        if (res.status === 409) return { result: 'refused', code: 'username_taken', detail: `The sign-in name "${person.username}" was taken while this was being done.` };
        await must(res, 'creating the person');
        const created = await byUsername(person.username);
        if (created === undefined) throw new DirectoryUnavailableError('created the person but cannot find them');
        id = created.id;
      }
      await setPassword(id, person.temporaryPassword);
      if (person.secondFactor) await mapSecondFactor(id);
      await setEnabled(id, true, 'switching the sign-in on');
      return { result: 'issued', resumed };
    },
    end: async (userId) => {
      const user = await byUserId(userId);
      if (user === undefined) return 'none';
      await setEnabled(user.id, false, 'switching the sign-in off');
      await must(await call('POST', `/users/${encodeURIComponent(user.id)}/logout`), 'ending the open sessions');
      return 'ended';
    },
  };
}
