// A shop's own realm file, made from the repository's realm (OB-15-d · OB-19 "A" · ADR-0019 §4 · M36-FR-01).
//
// The owner chose (OB-19) that head office never holds a key able to create realms: head office makes the file, and the
// administrator loads it at the identity server, once per new shop. Loaded by hand, the identity server fills in no
// `${…}` placeholder — so every value the repository's realm reads from the environment is written in here, literally:
// the realm's own name, the ONE shop it signs for, the shop's own web address, our API's name.
//
// What the file never carries: a person, a credential, a secret. The provisioner's secret is generated by the identity
// server when the file is loaded; the administrator copies it to head office (runbook).

export interface ShopRealmInput {
  /** The realm's name: sre-<shop>, lower case. */
  readonly realm: string;
  /** The shop (tenant) this realm signs for. */
  readonly tenantId: string;
  /** What people see as the realm's name on the identity server's own pages. */
  readonly displayName: string;
  /** The shop's screens' address (sign-in returns there): https, no path. */
  readonly webOrigin: string;
  /** Our API's name in the tokens. */
  readonly audience: string;
  /** Allow an http address (a test machine only). */
  readonly allowHttp?: boolean;
}

export type ShopRealmFile =
  | { readonly ok: true; readonly realm: Record<string, unknown> }
  | { readonly ok: false; readonly problems: readonly string[] };

const REALM_NAME = /^sre-[a-z0-9][a-z0-9-]{1,36}$/;
const TENANT = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
/** The placeholders the repository's realm reads, and nothing else may remain once they are written in. */
const PLACEHOLDER = /\$\{(SRE_[A-Z_]+)(:[^}]*)?\}/g;

/** Make a shop's realm file from the repository's realm (`template`, the parsed `realm-sre-store.json`). */
export function shopRealmFile(template: Record<string, unknown>, input: ShopRealmInput): ShopRealmFile {
  const problems: string[] = [];
  if (!REALM_NAME.test(input.realm)) problems.push(`The realm name "${input.realm}" must be sre-<shop>: lower case letters, digits and hyphens.`);
  if (input.realm === template['realm']) problems.push(`"${input.realm}" is the first shop's realm. A new shop needs its own name.`);
  if (!TENANT.test(input.tenantId)) problems.push('The shop id must be its tenant id (a UUID).');
  const name = input.displayName.trim();
  if (name.length < 2 || name.length > 80) problems.push('The shop\'s name must be 2 to 80 characters.');
  let origin: URL | undefined;
  try { origin = new URL(input.webOrigin); } catch { /* reported below */ }
  if (origin === undefined || origin.origin !== input.webOrigin.replace(/\/+$/, '')) {
    problems.push('The web address must be an address alone, like https://anna-nagar.<your domain> — no path.');
  } else if (origin.protocol !== 'https:' && !(input.allowHttp === true && origin.protocol === 'http:')) {
    problems.push('The web address must be https — a sign-in over plain http can be read on the way.');
  }
  if (input.audience.trim() === '') problems.push('The API\'s name (audience) is missing.');
  if (problems.length > 0) return { ok: false, problems };

  const values: Record<string, string> = {
    SRE_TENANT_ID: input.tenantId,
    SRE_WEB_ORIGIN: origin!.origin,
    SRE_API_AUDIENCE: input.audience.trim(),
  };
  const unknown = new Set<string>();
  const text = JSON.stringify(template).replace(PLACEHOLDER, (_whole, key: string) => {
    const v = values[key];
    if (v === undefined) { unknown.add(key); return ''; }
    return JSON.stringify(v).slice(1, -1);
  });
  if (unknown.size > 0) return { ok: false, problems: [`The repository's realm reads ${[...unknown].join(', ')}, which this tool does not know how to fill in.`] };
  const realm = JSON.parse(text) as Record<string, unknown>;
  realm['realm'] = input.realm;
  realm['displayName'] = name;
  // A file that still carries a person or a secret is not made at all.
  if (realm['users'] !== undefined && (realm['users'] as Record<string, unknown>[]).some((u) => u['credentials'] !== undefined || u['serviceAccountClientId'] === undefined)) {
    return { ok: false, problems: ['The repository\'s realm carries a person — it must not.'] };
  }
  if (/"(secret|password)"\s*:\s*"/i.test(JSON.stringify(realm))) {
    return { ok: false, problems: ['The repository\'s realm carries a secret — it must not.'] };
  }
  return { ok: true, realm };
}
