// ASN, direct-store-delivery, dock scheduling and handheld receiving (M07-FR-01).
//
// This is the handheld in the receiver's hand at the back door, and four things go
// wrong there that nothing downstream can fix:
//
//   1. THE DOUBLE SCAN. A case is scanned, the handheld hesitates, the receiver
//      scans again. Without a globally unique command id that is 48 units received
//      instead of 24 — and the error is invisible until a stock count months later.
//      So every scan carries an id and a repeat is a **no-op that says so** (§31.1).
//
//   2. THE CASE COUNTED AS ONE. A case of 24 scanned against a barcode the system
//      thinks is a single unit adds 1. Pack conversion is exact (M03-FR-02) or the
//      scan is refused; it is never guessed.
//
//   3. THE UNKNOWN BARCODE WAVED THROUGH. Under time pressure an unrecognised item
//      gets keyed in as "closest match". That is how a catalogue rots. An unknown
//      barcode goes to a **resolution queue** — the delivery continues, the item does
//      not silently become another item.
//
//   4. THE PRICE EDITED AT THE DOOR. A receiver can change quantities, conditions and
//      batches — that is their job. They can never change the agreed price, because
//      the whole three-way match depends on the PO price being the one that was
//      agreed, not the one that was convenient (§28).
//
// Direct-store-delivery — goods arriving with no purchase order — is legitimate
// (bread, milk, a supplier rep) and is the commonest route for goods to enter
// unaccounted. It gets a controlled path: allowed, but recorded as DSD, capped by
// value, and needing an approver above the receiver.
//
// Pure and deterministic: the timestamp is injected, there is no clock.

import type { Money } from '../../contracts/src/money';
import type { PackHierarchy } from '../../product/src/pack';
import { fromBaseUnits, unitsPerLevel } from '../../product/src/pack';

// --- dock scheduling ------------------------------------------------------------

export interface DockSlot {
  readonly slotId: string;
  readonly storeId: string;
  readonly dockId: string;
  /** ISO-8601 UTC. */
  readonly startsAt: string;
  readonly endsAt: string;
  readonly supplierId?: string;
  readonly poIds?: readonly string[];
  readonly status: 'booked' | 'arrived' | 'completed' | 'no_show' | 'cancelled';
}

export class DockConflictError extends Error {
  constructor(
    public readonly dockId: string,
    public readonly clashingSlotId: string,
  ) {
    super(
      `Dock "${dockId}" is already booked by slot "${clashingSlotId}" for that time — two lorries at one door is a queue, not a schedule`,
    );
    this.name = 'DockConflictError';
  }
}

/** Book a dock slot, refusing an overlap on the same door. */
export function bookDockSlot(slot: DockSlot, existing: readonly DockSlot[]): DockSlot {
  if (Date.parse(slot.endsAt) <= Date.parse(slot.startsAt)) {
    throw new DockConflictError(slot.dockId, '(invalid window)');
  }
  const clash = existing.find(
    (s) =>
      s.dockId === slot.dockId &&
      s.slotId !== slot.slotId &&
      s.status !== 'cancelled' &&
      s.status !== 'no_show' &&
      Date.parse(s.startsAt) < Date.parse(slot.endsAt) &&
      Date.parse(slot.startsAt) < Date.parse(s.endsAt),
  );
  if (clash) {
    throw new DockConflictError(slot.dockId, clash.slotId);
  }
  return slot;
}

// --- advance shipping notice ----------------------------------------------------

export interface AsnLine {
  readonly lineId: string;
  readonly productId: string;
  /** What the supplier says they sent, in base units. */
  readonly quantityMinor: number;
  readonly uom: string;
  readonly batchId?: string;
  readonly expiry?: string;
}

export interface Asn {
  readonly asnId: string;
  readonly supplierId: string;
  readonly poId?: string;
  readonly expectedAt: string;
  readonly lines: readonly AsnLine[];
}

// --- the receiving command ------------------------------------------------------

export type ReceiveSource = 'po' | 'asn' | 'dsd';

/**
 * One scan at the back door. `commandId` is generated by the handheld and is
 * **globally unique**; it is what makes a repeat harmless (§31.1).
 */
export interface ReceiveCommand {
  readonly commandId: string;
  readonly grnId: string;
  readonly storeId: string;
  readonly receivedBy: string;
  readonly at: string;
  readonly source: ReceiveSource;
  readonly poId?: string;
  readonly asnId?: string;
  /** The barcode actually scanned — which may be a case, not a unit. */
  readonly barcode: string;
  /** How many of THAT barcode were scanned (2 cases = 2). */
  readonly scannedQuantity: number;
  readonly batchId?: string;
  readonly expiry?: string;
  /** Present only for DSD, where there is no PO price to match against. */
  readonly declaredUnitCost?: Money;
}

export interface BarcodeResolution {
  readonly barcode: string;
  readonly productId: string;
  /** The pack level this barcode identifies — 'unit', 'case', … */
  readonly level: string;
}

export type ReceiveOutcome =
  | 'received'
  | 'duplicate_ignored'
  | 'unknown_barcode'
  | 'not_on_order'
  | 'dsd_needs_approval'
  | 'over_delivery_needs_approval'
  | 'price_change_refused';

export interface ReceiveResult {
  readonly commandId: string;
  readonly outcome: ReceiveOutcome;
  readonly accepted: boolean;
  readonly productId?: string;
  /** Base units actually received — the case conversion already applied. */
  readonly quantityMinor: number;
  readonly detail: string;
  /** Set when the item could not be identified and must be resolved by a person. */
  readonly resolutionRequired?: boolean;
}

export interface ReceivingPolicy {
  /** Over-delivery beyond the ordered quantity accepted without approval, in bp. */
  readonly overDeliveryToleranceBp: number;
  /** DSD is allowed at all. Some tenants refuse it outright. */
  readonly allowDsd: boolean;
  /** DSD value a receiver may accept unaided, in minor units. */
  readonly dsdApprovalAboveMinor: number;
}

export const DEFAULT_RECEIVING_POLICY: ReceivingPolicy = {
  overDeliveryToleranceBp: 200,
  allowDsd: true,
  dsdApprovalAboveMinor: 0, // every DSD needs a second person until the owner raises it
};

export interface ReceiveApproval {
  readonly subjectRef: string;
  readonly status: 'approved' | 'rejected' | 'pending';
  readonly decidedBy: string;
}

/**
 * What the purchase order says, as the RECEIVER sees it — read-only at the door.
 * Deliberately named apart from `OrderedLine` in `three-way-match.ts`: that one is
 * keyed by invoice line for matching, this one by product for scanning, and one
 * barrel cannot export two different shapes under one name.
 */
export interface OrderedProduct {
  readonly productId: string;
  readonly quantityMinor: number;
  readonly unitCost: Money;
}

/**
 * Process one scan. Everything already received in this GRN is passed in, so the
 * decision is a pure function of the facts — and a repeated `commandId` short-
 * circuits before any of the stateful checks, exactly as the cash and sale engines do.
 */
export function receiveScan(input: {
  readonly command: ReceiveCommand;
  /** Commands already applied to this GRN, by id. */
  readonly appliedCommandIds: readonly string[];
  readonly barcodes: readonly BarcodeResolution[];
  readonly packs: readonly PackHierarchy[];
  readonly ordered?: readonly OrderedProduct[];
  /** Base units already received against each product in this GRN. */
  readonly receivedSoFar?: Readonly<Record<string, number>>;
  readonly policy?: ReceivingPolicy;
  readonly approval?: ReceiveApproval;
}): ReceiveResult {
  const { command } = input;
  const policy = input.policy ?? DEFAULT_RECEIVING_POLICY;

  // 1. The double scan. Checked FIRST, before anything stateful, so a retry after a
  //    hesitating handheld is a genuine no-op rather than a second receipt.
  if (input.appliedCommandIds.includes(command.commandId)) {
    return {
      commandId: command.commandId,
      outcome: 'duplicate_ignored',
      accepted: false,
      quantityMinor: 0,
      detail: 'this scan has already been counted — scanning again changes nothing',
    };
  }

  // 2. The unknown barcode. It goes to a queue; it never becomes "closest match".
  const resolution = input.barcodes.find((b) => b.barcode === command.barcode.trim());
  if (!resolution) {
    return {
      commandId: command.commandId,
      outcome: 'unknown_barcode',
      accepted: false,
      quantityMinor: 0,
      detail: `barcode ${command.barcode} is not in the catalogue — it goes to the resolution queue; the delivery carries on`,
      resolutionRequired: true,
    };
  }

  // 3. The case counted as one. Conversion is exact or it is refused.
  const pack = input.packs.find((p) => p.productId === resolution.productId);
  let unitsPerScan = 1;
  if (resolution.level !== 'unit') {
    if (!pack) {
      return {
        commandId: command.commandId,
        outcome: 'unknown_barcode',
        accepted: false,
        quantityMinor: 0,
        detail: `barcode ${command.barcode} is a "${resolution.level}" but this product has no pack definition — the unit count would be a guess`,
        resolutionRequired: true,
      };
    }
    unitsPerScan = unitsPerLevel(pack, resolution.level);
  }
  const quantityMinor = command.scannedQuantity * unitsPerScan;

  // 4. The price edited at the door.
  if (command.source !== 'dsd' && command.declaredUnitCost !== undefined) {
    const orderedLine = input.ordered?.find((l) => l.productId === resolution.productId);
    if (orderedLine && orderedLine.unitCost.minor !== command.declaredUnitCost.minor) {
      return {
        commandId: command.commandId,
        outcome: 'price_change_refused',
        accepted: false,
        productId: resolution.productId,
        quantityMinor: 0,
        detail:
          'a receiver may correct quantities, batches and condition, never the agreed price — the three-way match depends on the price that was agreed, not the one that was convenient (§28)',
      };
    }
  }

  // 5. Direct-store-delivery: legitimate, and the commonest way goods enter
  //    unaccounted, so it is allowed on a controlled path rather than freely.
  if (command.source === 'dsd') {
    if (!policy.allowDsd) {
      return {
        commandId: command.commandId,
        outcome: 'not_on_order',
        accepted: false,
        productId: resolution.productId,
        quantityMinor: 0,
        detail: 'this store does not accept deliveries without a purchase order',
      };
    }
    const value = (command.declaredUnitCost?.minor ?? 0) * quantityMinor;
    const approved =
      input.approval?.status === 'approved' &&
      input.approval.subjectRef === command.grnId &&
      input.approval.decidedBy !== command.receivedBy;
    if (value > policy.dsdApprovalAboveMinor && !approved) {
      return {
        commandId: command.commandId,
        outcome: 'dsd_needs_approval',
        accepted: false,
        productId: resolution.productId,
        quantityMinor: 0,
        detail: `${quantityMinor} unit(s) arriving with no purchase order needs a second person's approval before it enters stock`,
      };
    }
    return {
      commandId: command.commandId,
      outcome: 'received',
      accepted: true,
      productId: resolution.productId,
      quantityMinor,
      detail: `${quantityMinor} unit(s) received as a direct-store-delivery${
        approved ? ` (approved by ${input.approval?.decidedBy})` : ''
      }`,
    };
  }

  // 6. Against a PO or an ASN: is this even on the order?
  const orderedLine = input.ordered?.find((l) => l.productId === resolution.productId);
  if (input.ordered !== undefined && !orderedLine) {
    return {
      commandId: command.commandId,
      outcome: 'not_on_order',
      accepted: false,
      productId: resolution.productId,
      quantityMinor: 0,
      detail: 'this product is not on the purchase order — receive it as a DSD if it is genuinely being delivered',
    };
  }

  if (orderedLine) {
    const already = input.receivedSoFar?.[resolution.productId] ?? 0;
    const total = already + quantityMinor;
    const tolerated = Math.floor(
      orderedLine.quantityMinor + (orderedLine.quantityMinor * policy.overDeliveryToleranceBp) / 10_000,
    );
    if (total > tolerated) {
      const approved =
        input.approval?.status === 'approved' &&
        input.approval.subjectRef === command.grnId &&
        input.approval.decidedBy !== command.receivedBy;
      if (!approved) {
        return {
          commandId: command.commandId,
          outcome: 'over_delivery_needs_approval',
          accepted: false,
          productId: resolution.productId,
          quantityMinor: 0,
          detail: `${total} would exceed the ordered ${orderedLine.quantityMinor} beyond tolerance — over-delivery is stock you did not choose to buy, so it needs approval`,
        };
      }
    }
  }

  return {
    commandId: command.commandId,
    outcome: 'received',
    accepted: true,
    productId: resolution.productId,
    quantityMinor,
    detail:
      unitsPerScan === 1
        ? `${quantityMinor} unit(s) received`
        : `${command.scannedQuantity} × ${resolution.level} = ${quantityMinor} unit(s) received`,
  };
}

export interface AsnComparison {
  readonly productId: string;
  readonly advisedMinor: number;
  readonly receivedMinor: number;
  readonly differenceMinor: number;
  readonly detail: string;
}

/**
 * Compare what the supplier ADVISED with what actually turned up. The ASN is a
 * promise, not a receipt — treating it as one is how a shop books stock it never
 * got. Differences here feed the discrepancy path (M07-FR-03).
 */
export function compareAgainstAsn(
  asn: Asn,
  received: Readonly<Record<string, number>>,
): readonly AsnComparison[] {
  const products = new Set([...asn.lines.map((l) => l.productId), ...Object.keys(received)]);
  return [...products]
    .sort()
    .map((productId) => {
      const advised = asn.lines
        .filter((l) => l.productId === productId)
        .reduce((s, l) => s + l.quantityMinor, 0);
      const got = received[productId] ?? 0;
      const difference = got - advised;
      return {
        productId,
        advisedMinor: advised,
        receivedMinor: got,
        differenceMinor: difference,
        detail:
          difference === 0
            ? 'matches the advice note'
            : difference < 0
              ? `${-difference} fewer than advised — the note is a promise, not a receipt`
              : `${difference} more than advised`,
      };
    })
    .filter((c) => c.differenceMinor !== 0);
}

/** Convert accepted base units back into whole cases plus a remainder, for the GRN. */
export function summariseByPack(
  pack: PackHierarchy,
  baseUnits: number,
  level: string,
): { readonly packs: number; readonly remainderBaseUnits: number } {
  return fromBaseUnits(pack, baseUnits, level);
}
